// Subjects which have been approved by  by the authority
export default [
  'Math',
  'Ukrainian',
  'Art',
  'Business studies',
  'Citizenship',
  'Dance',
  'Design & technology',
  'Drama',
  'English',
  'Geography',
  'History',
  'Information and communication technology (ICT)',
  'Languages',
  'Mathematics',
  'Modern studies',
  'Music',
  'PE: Physical education',
  'PSHE: Personal, social and health education (PSHE)',
  'RE: Religious education',
  'Science',
  'Study skills',
  'Biology',
  'Chemistry',
  'Commerce',
  'Computer studies.',
  'Design technology',
  'Drama',
  'Ethic',
  'Physics',
  'Psychology',
]
